module.exports = productsData = [
    {
      id: 1,
      name: 'Auriculares Apple Earpods Con Conector 3.5mm Original Caja',
      href: '#',
      imageSrc: 'https://i.ibb.co/YXrDx0v/APPLE1.webp',
      imageAlt: "Auriculares Apple Earpods Con Conector 3.5mm Original Caja",
      price: 35999,
      stock: 10,
      brand: 'Apple',
      category: "Auricular",
      description: "Tonos de graves más profundos y ricos. Mayor protección contra el sudor yel agua. Controla la reproducción de música y video. Responder y finalizar llamadas.Especificaciones técnicas General. Con control remoto y micrófono."
    },
    {
      id: 2,
      name: 'Apple AirPods Max',
      href: '#',
      imageSrc: 'https://i.ibb.co/3vdN30h/APPLE2.webp',
      imageAlt: "Auriculares Apple Earpods Con Conector 3.5mm Original Caja",
      price: 351999,
      stock: 10,
      brand: 'Apple',
      category: "Auricular",
      description: "Los AirPods Max reinventan los audífonos de diadema. El controlador    dinámico diseñado por Apple te ofrece un sonido inmersivo de alta fidelidad. Cada elemento,desde la diadema hasta las almohadillas, está pensado para brindarte un ajuste excepcional. LaCancelación Activa de Ruido líder en la industria bloquea el ruido exterior, y el modo Ambiente te permite escuchar todo lo que ocurre a tu alrededor. Además, el audio espacial conseguimiento dinámico del movimiento de la cabeza crea un sonido envolvente como siestuvieras en el cine."
    },
    {
      id: 3,
      name: 'Apple AirPods (3ª generación) con estuche de carga MagSafe',
      href: '#',
      imageSrc: 'https://i.ibb.co/Mp3yNSq/APPLE3.webp',
      imageAlt: "Apple AirPods (3ª generación) con estuche de carga MagSafe",
      price: 116839,
      stock: 10,
      brand: 'Apple',
      category: "Auricular",
      description: "El audio espacial funciona con películas, programas de TV y videos en app compatibles. Requiere un iPhone o iPad. La duración de la batería varía según el uso y la configuración. Para obtener más información, visita apple.com/mx/batteries. Los AirPods(tercera generación) son resistentes al agua y al sudor al hacer ejercicio o practicar deportes no acuáticos. Los AirPods (tercera generación) fueron probados en condiciones de laboratoriocontroladas y tienen una clasificación IPX4 según la norma IEC 60529. La resistencia al agua y alsudor no es una condición permanente, y podría disminuir como consecuencia del uso normal.No intentes cargar los AirPods (tercera generación) si están mojados. Requiere una cuenta deiCloud y macOS 15.1, iOS 15.1, iPadOS, watchOS 8.1 o tvOS 15.1 o posterior."
    },
    {
      id: 4,
      name: 'Apple AirPods (segunda Generacion) Con Estuche De Carga Orig.',
      href: '#',
      imageSrc: 'https://i.ibb.co/KbGHXdV/APPLE4.webp',
      imageAlt: "Apple AirPods (segunda Generacion) Con Estuche De Carga Orig.",
      price: 78459,
      stock: 10,
      brand: 'Apple',
      category: "Auricular",
      description: "Los AirPods te brindan una experiencia inalámbrica increíble, pues ahora teofrecen muchas horas de audio y conversación y la posibilidad de usarlos con un estuche decarga inalámbrica. Sácalos del estuche y estarán listos para funcionar con todos tusdispositivos. Póntelos y se conectarán al instante, como por arte de magia, para brindarte unsonido rico en matices y de alta calidad."
    },
    {
      id: 5,
      name: 'Apple AirPods Pro',
      href: '#',
      imageSrc: 'https://i.ibb.co/5585sCJ/APPLE5.webp',
      imageAlt: "Apple AirPods Pro",
      price: 92999,
      stock: 10,
      brand: 'Apple',
      category: "Auricular",
      description: "Cancelación Activa de Ruido para que disfrutes de un sonido inmersivo.Modo Ambiente para que escuches todo lo que ocurre a tu alrededor y puedas interactuar contu entorno. Ajuste personalizable para que los uses con comodidad todo el día. Y resistencia alagua y al sudor (1). Los AirPods Pro tienen un diseño increíblemente ligero y se configuranfácilmente en todos tus dispositivos Apple (2)."
    },
    {
      id: 6,
      name: 'Apple EarPods con conector Lightning',
      href: '#',
      imageSrc: 'https://i.ibb.co/Phd98yS/APPLE6.webp',
      imageAlt: "Apple EarPods con conector Lightning",
      price: 16699,
      stock: 10,
      brand: 'Apple',
      category: "Auricular",
      description: "A diferencia de los audífonos circulares tradicionales, el diseño de los EarPodsse basa en la geometría del oído, por eso son más cómodos que cualquier otro audífono deeste tipo.Las bocinas del interior de los EarPods han sido diseñadas para mejorar la calidad del sonido yminimizar su pérdida. ¿El resultado? Un audio de alta calidad.Los EarPods con conector Lightning también incluyen un control remoto integrado en el cableque te permite ajustar el volumen, controlar la reproducción de música y video, y responder ofinalizar llamadas."
    },
    {
      id: 7,
      name: 'Auriculares Motorola Wired 105',
      href: '#',
      imageSrc: 'https://i.ibb.co/z5M5Ftp/MOTO7.webp',
      imageAlt: "Auriculares Motorola Wired 105",
      price: 2799,
      stock: 10,
      brand: 'Motorola',
      category: "Auricular",
      description: "Material: Plástico. Cable de PU Color: Negro / Blanco. Diseño confortable en oreja. Ponente: 13.5MM. Conector: 3.5MM niquelado. Control: botón de llamada / reproducción. Rango de frecuencia: 20Hz-20KHz. Largo del cable: 1.5 metros. Compatibilidad: multiplataforma"
    },
    {
      id: 8,
      name: 'Auriculares Motorola Motobuds 085 Bluetooth Ipx5',
      href: '#',
      imageSrc: 'https://i.ibb.co/Z1WXXM5/MOTO8.webp',
      imageAlt: "Auriculares Motorola Motobuds 085 Bluetooth Ipx5",
      price: 17499,
      stock: 10,
      brand: 'Motorola',
      category: "Auricular",
      description: "Con estuche de carga. Con micrófono incorporado. Resistentes al agua. Sonido superior y sin límites. Cómodos y prácticos."
    },
    {
      id: 9,
      name: 'Auriculares in-ear inalámbricos Motorola VerveBuds 100 SH052 ',
      href: '#',
      imageSrc: 'https://i.ibb.co/cDjSpdq/MOTO9.webp',
      imageAlt: "Auriculares in-ear inalámbricos Motorola VerveBuds 100 SH052",
      price: 52999,
      stock: 10,
      brand: 'Motorola',
      category: "Auricular",
      description: " Al ser in-ear, mejoran la calidad del audio y son de tamaño pequeño para poder insertarse en tu oreja. Son ideales para acompañarte a la hora de hacer ejercicio mientras te sumergís en el mejor sonido envolvente. Wireless al 100%. A diferencia de otras conectividades, este dispositivo está fabricado con tecnología TWS (True Wireless Stereo). La misma permite una conexión inalámbrica total y funciona sin un solo cable entre pares. Con ella podrás disfrutar del entorno sonoro sin necesidad de estar pendiente de conexiones físicas."
    },
    {
      id: 10,
      name: 'Motorola Verveloop 2+ Auriculares Estéreo Inalámbricos Súper',
      href: '#',
      imageSrc: 'https://i.ibb.co/yRFPFn4/MOTO10.webp',
      imageAlt: "Auriculares in-ear inalámbricos Motorola VerveBuds 100 SH052 negro",
      price: 33699,
      stock: 10,
      brand: 'Motorola',
      category: "Auricular",
      description: " Ganchos para las orejas integrados para mayor comodidad durante cualquier actividad, además de resistente al sudor y al agua con clasificación IP57. Cuenta con hasta 10 horas de reproducción y un alcance de hasta 60 pies. Compatible con Siri, Google Now y Alexa. Micrófono integrado para alternar fácilmente entre música y llamadas. Encuentra la última ubicación conectada en un mapa con Hubble Connect for Verve Life."
    },
    {
      id: 11,
      name: 'Auricular Motorola Xt500 Plus Bluetooth Manos Libres',
      href: '#',
      imageSrc: 'https://i.ibb.co/xjVwcCL/MOTO11.webp',
      imageAlt: "Auricular Motorola Xt500 Plus Camo Bluetooth Manos Libres",
      price: 31998,
      stock: 10,
      brand: 'Motorola',
      category: "Auricular",
      description: "Alcance inalámbrico de 10 m. La batería dura 25 h. Modo manos libres incluido. Con micrófono incorporado. Resistentes al agua y al polvo. Su clasificación IP es IPX4. Sonido superior y sin límites. Cómodos y prácticos. La duración de la batería depende del uso que se le dé al producto. Tamaño del altavoz: 40mm. Las imágenes pueden ser ilustrativas."
    },
    {
      id: 12,
      name: 'Auricular Motorola Xt200 Manos Libres Plug 3,5mm',
      href: '#',
      imageSrc: 'https://i.ibb.co/K6RGSwF/MOTO12.webp',
      imageAlt: "Auricular Motorola Xt200 Manos Libres Plug 3,5mm",
      price: 21999,
      stock: 10,
      brand: 'Motorola',
      category: "Auricular",
      description: "Modo manos libres incluido. Con micrófono incorporado. Sonido superior y sin límites. Cómodos y prácticos. Tamaño del altavoz: 40mm. Las imágenes pueden ser ilustrativas."
    },
    {
      id: 13,
      name: 'Auriculares Samsung Original',
      href: '#',
      imageSrc: 'https://i.ibb.co/MNhXgK3/SAMSUNG13.webp',
      imageAlt: "Auriculares Samsung Origina",
      price: 3159,
      stock: 10,
      brand: 'Samsung',
      category: "Auricular",
      description: "Con micrófono incorporado. El largo del cable es de 120 m. Sonido superior y sin límites. Cómodos y prácticos. Tamaño del altavoz: 3.5mm.s"
    },
    {
      id: 14,
      name: 'Auriculares in-ear inalámbricos Samsung Galaxy Buds Live SM-R180NZ mystic',
      href: '#',
      imageSrc: 'https://i.ibb.co/tBdJsDJ/SAMSUNG14.webp',
      imageAlt: "Auriculares in-ear inalámbricos Samsung Galaxy Buds Live SM-R180NZ mystic",
      price: 5999,
      stock: 10,
      brand: 'Samsung',
      category: "Auricular",
      description: "Cuenta con tecnología True Wireless. Alcance inalámbrico de 10 m. La batería dura 6 h. Modo manos libres incluido. Asistente de voz integrado: Bixby. Con cancelación de ruido. Con estuche de carga inalámbrica. Con micrófono incorporado. Resistentes al agua. Su clasificación IP es IPX2. Sonido superior y sin límites. Cómodos y prácticos. La duración de la batería depende del uso que se le dé al producto. Cuenta con sensores de proximidad. Tamaño del altavoz: 12mm. Posee 6 micrófonos para llamadas de voz más nítidas."
    },
    {
      id: 15,
      name: 'Auriculares Samsung By Akg Original Conector Tipo C Type C',
      href: '#',
      imageSrc: 'https://i.ibb.co/2Y7pnGN/SAMSUNG15.webp',
      imageAlt: "Auriculares in-ear inalámbricos Samsung Galaxy Buds Live SM-R180NZ mystic black",
      price: 11449,
      stock: 10,
      brand: 'Samsung',
      category: "Auricular",
      description: "Con micrófono incorporado. Sonido superior y sin límites. Cómodos y prácticos."
    },
    {
      id: 16,
      name: 'SAMSUNG16',
      href: '#',
      imageSrc: 'https://i.ibb.co/JQPcg0g/SAMSUNG16.webp',
      imageAlt: "SAMSUNG16",
      price: 36955,
      stock: 10,
      brand: 'Samsung',
      category: "Auricular",
      description: "Auriculares inalámbricos. Estos versátiles auriculares, tanto con cable como inalámbricos, son la solución perfecta para los consumidores que desean combinar una calidad de audio excepcional con un diseño elegante. Level On Wireless funciona en cualquier dispositivo con tecnología Bluetooth integrada o conectividad de 3,5 mm. Sonido de estudio con cancelación de ruido. Los controladores de 40 mm de alta definición se combinan con 4 MIC Active Noise Cancellation y la tecnología de sonido aptX® para brindar un sonido excepcionalmente claro con un rango dinámico completo y graves potentes a cualquier volumen."
    },
    {
      id: 17,
      name: 'Auriculares Inalambricos Plegables Con Bluetooth',
      href: '#',
      imageSrc: 'https://i.ibb.co/SQJDW4c/SAMSUNG17.webp',
      imageAlt: "Auriculares Inalambricos Plegables Con Bluetooth, Color Rosa",
      price: 164749,
      stock: 10,
      brand: 'Samsung',
      category: "Auricular",
      description: "Aautomatizacion de reproduccion y pausa: sus auriculares se pausaran automaticamente cuando se los quiten y reanudaran la reproduccion automaticamente cuando los vuelva a colocar sobre las orejas. Bateria de larga duracion/carga rapida: disfrute de hasta 33 horas de la musica que inspira su dia. con una recarga rapida de 5 minutos, puede mantener la musica durante una hora adicional. Carga rapida: la recarga de 5 minutos agregara otra hora de musica para ayudarte en tu viaje. Conectividad multipunto: empareje dos dispositivos bluetooth a la vez y sus auriculares cambiaran intuitivamente entre dispositivos."
    },
    {
      id: 18,
      name: 'Auriculares in-ear gamer inalámbricos Samsung Galaxy Buds2 Pro SM-R510 graphite',
      href: '#',
      imageSrc: 'https://i.ibb.co/86MtQJD/SAMSUNG18.webp',
      imageAlt: "Auriculares in-ear gamer inalámbricos Samsung Galaxy Buds2 Pro SM-R510 graphite",
      price: 83459,
      stock: 10,
      brand: 'Samsung',
      category: "Auricular",
      description: "Cuenta con tecnología True Wireless. Alcance inalámbrico de 10 m. La batería dura 5 h. Tiene una memoria de 1.5 GB. Modo manos libres incluido. Asistente de voz integrado: Bixby. Con cancelación de ruido. Con estuche de carga inalámbrica. Con micrófono incorporado. Resistentes al agua y al polvo. Su clasificación IP es IPX7. Uso apto para deporte. Sonido superior y sin límites. Cómodos y prácticos. La duración de la batería depende del uso que se le dé al producto. Cuenta con sensores de proximidad. Tamaño del altavoz: 10mm."
    },
    {
      id: 19,
      name: 'Auriculares Deportivos Xiaomi Bt 5.2 Batería 12hs Pcreg',
      href: '#',
      imageSrc: 'https://i.ibb.co/kmZL3NM/XIAOMI19.jpg',
      imageAlt: "Auriculares Deportivos Xiaomi Bt 5.2 Batería 12hs Pcreg",
      price: 88549,
      stock: 10,
      brand: 'Xiaomi',
      category: "Auricular",
      description: "PESO: 28 gramos. UNIDAD DE DIAFRAGMA:Diafragmas de conducción ósea. CONEXIÓN: Bluetooth 5.2. COMPATIBILIDAD: Android y Ios. 165 mAh. Hasta 12 horas de uso. Tecnología Qualcomm cVc para cancelación de ruido en llamadas. Resistencia IP66. Compatible con los códecs aptX Adaptative, aptX y SBC."
    },
    {
      id: 20,
      name: 'Auriculares in-ear inalámbricos Xiaomi Mi Earphones 2 Basic TWSEJ08WM',
      href: '#',
      imageSrc: 'https://i.ibb.co/XkGKYLm/XIAOMI20.webp',
      imageAlt: "Auriculares in-ear inalámbricos Xiaomi Mi Earphones 2 Basic TWSEJ08WM",
      price: 14947,
      stock: 10,
      brand: 'Xiaomi',
      category: "Auricular",
      description: "Cuenta con tecnología True Wireless. Alcance inalámbrico de 10 m. La batería dura 5 h. Modo manos libres incluido. Con cancelación de ruido. Con estuche de carga inalámbrica. Con micrófono incorporado. Resistentes al agua. El largo del cable es de 1.25 m. Sonido superior y sin límites. Cómodos y prácticos. La duración de la batería depende del uso que se le dé al producto. Tamaño del altavoz: 14.2mm."
    },
    {
      id: 21,
      name: 'Auriculares Xiaomi Redmi Buds 4 Lite Inalámbricos Bluetooth.',
      href: '#',
      imageSrc: 'https://i.ibb.co/PTxBHcs/XIAOMI21.webp',
      imageAlt: "Auriculares Xiaomi Redmi Buds 4 Lite Inalámbricos Bluetooth.",
      price: 19997,
      stock: 10,
      brand: 'Xiaomi',
      category: "Auricular",
      description: " Bluetooth 5.3 - Más rápido y estable. Modo de baja latencia. Cancelación de ruido de IA para llamadas. Ligero y portáti. Hasta 20 horas de duración de la batería con funda de carga. Obtén una experiencia auditiva inmersiva durante más tiempo: los auriculares se pueden utilizar hasta 5 horas con una sola carga, y hasta 20 horas con la funda de carga portátil, para que puedas disfrutar de una gran música día y noche. Resistencia al polvo y al agua IP54."
    },
    {
      id: 22,
      name: 'Auriculares Xiaomi Basic Con Micrófono Para Celular Original.',
      href: '#',
      imageSrc: 'https://i.ibb.co/Jyc8TNv/XIAOMI22.webp',
      imageAlt: "Auriculares Xiaomi Basic Con Micrófono Para Celular Original.",
      price: 7399,
      stock: 10,
      brand: 'Xiaomi',
      category: "Auricular",
      description: "  Modelo: Mi in Ear Headphones Basic. Modelo alfanumérico: HSEJ03JY. Material: Silicona, Metal. Color: elegir entre NEGRO, PLATA, Y CELESTE ( es lo que este disponible en las variantes ). Funciones: contestar llamadas ,pausar y despausar canciones. "
    },
    {
      id: 23,
      name: 'Auriculares Bluetooth Xiaomi Redmi Buds 3 Lite In Ear.',
      href: '#',
      imageSrc: 'https://i.ibb.co/MM5h4zq/XIAOMI23.webp',
      imageAlt: "Auriculares Bluetooth Xiaomi Redmi Buds 3 Lite In Ear.",
      price: 19999,
      stock: 10,
      brand: 'Xiaomi',
      category: "Auricular",
      description: "  El diseño ergonómico brinda comodidad sin esfuerzo y mantiene a Redmi Buds 3 Lite seguro en sus oídos incluso durante el ejercicio. Duración de la batería de los auriculares - Aprox. 5 horas. Duración de la batería del estuche de carga - Aprox. 18 horas. "
    },
    {
      id: 24,
      name: 'Auriculares Inalámbricos Xiaomi Redmi Buds Essential',
      href: '#',
      imageSrc: 'https://i.ibb.co/BqZwXbw/XIAOMI24.webp',
      imageAlt: "Auriculares Inalámbricos Xiaomi Redmi Buds Essential",
      price: 21999,
      stock: 10,
      brand: 'Xiaomi',
      category: "Auricular",
      description: " Conexión inalámbrica: Bluetooth 5.2. Capacidad de la batería de los auriculares: 43 mAh.Capacidad de la batería del estuche de carga: 300mAh. Distancia de conexión: 10m (espacio abierto libre de obstáculos). "
    },
    {
      id: 25,
      name: 'Auriculares In-ear Inalámbricos Xiaomi Redmi Buds 3 ',
      href: '#',
      imageSrc: 'https://i.ibb.co/3fkcvZS/XIAOMI25.webp',
      imageAlt: "Auriculares In-ear Inalámbricos Xiaomi Redmi Buds 3 Blaco",
      price: 18999,
      stock: 10,
      brand: 'Xiaomi',
      category: "Auricular",
      description: " Al ser in-ear, mejoran la calidad del audio y son de tamaño pequeño para poder insertarse en tu oreja. Son ideales para acompañarte a la hora de hacer ejercicio mientras te sumergís en el mejor sonido envolvente. Wireless al 100%. "
    },
    {
      id: 26,
      name: 'Apple iPhone 11',
      href: '#',
      imageSrc: 'https://i.ibb.co/4Pg8rYN/Apple-i-Phone-11.webp',
      imageAlt: "Apple iPhone 11 (128 GB) ",
      price: 413899,
      brand: 'Apple',
      min: 1,
      stock: 10,
      category: "Celular",
      description: "Graba videos 4K y captura retratos espectaculares y paisajes increíbles con el sistema de dos cámaras. Toma grandes fotos con poca luz gracias al modo Noche. Disfruta colores reales en las fotos, videos y juegos con la pantalla Liquid Retina de 6.1 pulgadas (3). Aprovecha un rendimiento sin precedentes en los juegos, la realidad aumentada y la fotografía con el chip A13 Bionic. Haz mucho más sin necesidad de volver a cargar el teléfono gracias a su batería de larga duración (2). Y no te preocupes si se moja, el iPhone 11 tiene una resistencia al agua de hasta 30 minutos a una profundidad máxima de 2 metros (1)."
    },
    {
      id: 27,
      name: 'Apple iPhone 13',
      href: '#',
      imageSrc: 'https://i.ibb.co/C5L8wLV/APPLE-IPHONE-13.webp',
      imageAlt: "Apple iPhone 13 (128 GB)",
      price: 569999,
      brand: 'Apple',
      min: 1,
      stock: 10,
      category: "Celular",
      description: "El sistema de dos cámaras más avanzado en un iPhone. El superrápido chip A15 Bionic. Un gran salto en duración de batería. Un diseño resistente. Y una pantalla Super Retina XDR más brillante."
    },
    {
      id: 28,
      name: 'Apple iPhone 12 PRO MAX',
      href: '#',
      imageSrc: 'https://i.ibb.co/R4X4CBY/Apple-i-Phone-12-PRO-MAX.webp',
      imageAlt: "Apple iPhone 12 Pro Max (256 GB)",
      price: 829999,
      brand: 'Apple',
      min: 1,
      stock: 10,
      category: "Celular",
      description: "El iPhone 12 Pro Max tiene una pantalla Super Retina XDR más grande, de 6.7 pulgadas (1). Con el nuevo Ceramic Shield, es cuatro veces más resistente a las caídas (2). Y te permite tomar fotos increíbles con poca luz gracias al mejor sistema de cámaras Pro de un iPhone y al rango de zoom óptico de 5x. También puedes grabar, editar y reproducir video en Dolby Vision con calidad cinematográfica, tomar retratos con modo Noche y disfrutar experiencias de realidad aumentada de última generación con el escáner LiDAR. El iPhone 12 Pro Max viene con el potente chip A14 Bionic y es compatible con los nuevos accesorios MagSafe, que se adhieren magnéticamente a tu iPhone y brindan una carga inalámbrica más rápida (3). Una infinidad de posibilidades que no dejarán de sorprenderte."
    },
    {
      id: 29,
      name: 'Apple iPhone 14 Pro Max',
      href: '#',
      imageSrc: 'https://i.ibb.co/2PSWhSN/Apple-i-Phone-14-PRO-MAX.webp',
      imageAlt: "Apple iPhone 14 Pro Max (128 GB)",
      price: 918999,
      brand: 'Apple',
      min: 1,
      stock: 10,
      category: "Celular",
      description: "El iPhone 14 Pro Max te permite captar detalles increíbles gracias a su cámara gran angular de 48 MP. Además, trae la Dynamic Island y una pantalla siempre activa, para que puedas interactuar con tu iPhone de una forma completamente nueva. Y viene con Detección de Choques(1), una funcionalidad de seguridad que pide ayuda cuando no estás en condiciones de hacerlo."
    },
    {
      id: 30,
      name: 'Apple iPhone SE (3rd Generation)',
      href: '#',
      imageSrc: 'https://i.ibb.co/3kqNMLt/Apple-i-Phone-SE.webp',
      imageAlt: "Apple iPhone SE (3ª generación, 64 GB)",
      price: 323999,
      brand: 'Apple',
      min: 1,
      stock: 10,
      category: "Celular",
      description: "Chip A15 Bionic superrápido. Una increíble duración de batería y una cámara que es una superestrella. Y además, el vidrio más resistente en un smartphone y botón de inicio con la seguridad de Touch ID."
    },
    {
      id: 31,
      name: 'iPhone X',
      href: '#',
      imageSrc: 'https://i.ibb.co/qBCgqb3/Apple-i-Phone-X.webp',
      imageAlt: "iPhone X 64gb",
      price: 225999,
      brand: 'Apple',
      min: 1,
      stock: 10,
      category: "Celular",
      description: "El Apple iPhone X es una demostración de fuerza de Apple, mostrando lo que es capaz de hacer y para celebrar los 10 años del iPhone. El iPhone X cuenta con una pantalla de 5.8 pulgadas que abarca todo el frente del teléfono, dejando un espacio arriba para acomodar todos los sensores que contribuyen a Face ID, el nuevo método de desbloqueo por rostro, ya que el botón Touch ID desaparece. Con una atípica resolución de 2436 x 1125 pixels, acomoda 458ppi. Por dentro, el iPhone X tiene el nuevo procesador A11 Bionic. La cámara es dual de 12 MP similar a la del iPhone 8, es resistente al agua y corre iOS 11."
    },
    {
      id: 32,
      name: 'Xiaomi Pocophone Poco F5 Dual SIM 256 GB negro 12 GB RAM',
      href: '#',
      imageSrc: 'https://i.ibb.co/d0QyFrh/XIAOMI-POCO-PHONE-F5-DUAL-SIM.webp',
      imageAlt: "Xiaomi Pocophone Poco F5 Dual SIM",
      price: 471999,
      brand: 'Xiaomi',
      min: 1,
      stock: 10,
      category: "Celular",
      description: "Dispositivo liberado para que elijas la compañía telefónica que prefieras. Compatible con redes 5G. Pantalla AMOLED de 6.67. Tiene 3 cámaras traseras de 64Mpx/8Mpx/2Mpx. Cámara delantera de 16Mpx. Procesador Snapdragon 7+ Gen 2 Octa-Core de 2.91GHz con 12GB de RAM. Batería de 5000mAh. Memoria interna de 256GB. Resistente a las salpicaduras. Con reconocimiento facial y sensor de huella dactilar. Resistente al polvo."
    },
    {
      id: 33,
      name: 'Xiaomi Pocophone Poco M4 Pro Dual SIM 128 GB poco yellow 6 GB RAM',
      href: '#',
      imageSrc: 'https://i.ibb.co/LYvNzqw/XIAOMI-POCO-PHONE-M4-PRO-DUAL-SIM.webp',
      imageAlt: "Xiaomi Pocophone Poco M4 Pro Dual SIM",
      price: 159999,
      brand: 'Xiaomi',
      min: 1,
      stock: 10,
      category: "Celular",
      description: "Dispositivo liberado para que elijas la compañía telefónica que prefieras. Pantalla AMOLED de 6.43. Tiene 3 cámaras traseras de 64Mpx/8Mpx/2Mpx. Cámara delantera de 16Mpx. Procesador MediaTek Helio G96 Octa-Core de 2.05GHz con 6GB de RAM. Batería de 5000mAh. Memoria interna de 128GB. Resistente a las salpicaduras. Con reconocimiento facial y sensor de huella dactilar. Resistente al polvo."
    },
    {
      id: 34,
      name: 'Xiaomi Redmi 9A Dual SIM 32 GB ',
      href: '#',
      imageSrc: 'https://i.ibb.co/yfSTNrs/XIAOMI-REDMI-9-A-DUAL-SIM.webp',
      imageAlt: "Xiaomi Redmi 9A Dual SIM 32 GB",
      price: 59999,
      brand: 'Xiaomi',
      min: 1,
      stock: 10,
      category: "Celular",
      description: "Dispositivo liberado para que elijas la compañía telefónica que prefieras. Pantalla IPS de 6.53. Cámaras delanteras de 5Mpx. Procesador MediaTek MT6762G Helio G25 Octa-Core de 2GHz con 2GB de RAM. Batería de 5000mAh. Memoria interna de 32GB. Con reconocimiento facial."
    },
    {
      id: 35,
      name: 'Xiaomi Redmi 9C Dual SIM 32 GB',
      href: '#',
      imageSrc: 'https://i.ibb.co/HGMJqq6/XIAOMI-REDMI-9-C-DUAL-SIM.webp',
      imageAlt: "Xiaomi Redmi 9C Dual SIM 32 GB",
      price: 65999,
      brand: 'Xiaomi',
      min: 1,
      stock: 10,
      category: "Celular",
      description: "Dispositivo liberado para que elijas la compañía telefónica que prefieras. 3 cámaras traseras de 13 Mpx, 2 Mpx y 2 Mpx con inteligencia artificial. Lente macro y sensor de profundidad. Cámara frontal de 5 Mpx con modo belleza. Procesador con tecnología HyperEngine para una experiencia de juego fluida y con gráficos realistas. Batería de larga duración para que disfrutes de más de 20 h de reproducción de video. Pantalla HD+ que brinda una visión envolvente y evita el cansancio visual."
    },
    {
      id: 36,
      name: 'Xiaomi Redmi 10C Dual SIM 128 GB',
      href: '#',
      imageSrc: 'https://i.ibb.co/cvFGn4c/XIAOMI-REDMI-10-C-DUAL-SIM.webp',
      imageAlt: "Xiaomi Redmi 10C Dual SIM 128 GB",
      price: 89999,
      brand: 'Xiaomi',
      min: 1,
      stock: 10,
      category: "Celular",
      description: "Dispositivo liberado para que elijas la compañía telefónica que prefieras. Pantalla IPS de 6.71. Tiene 2 cámaras traseras de 50Mpx/2Mpx. Cámara delantera de 5Mpx. Procesador Snapdragon 680 Octa-Core de 2.4GHz con 4GB de RAM. Batería de 5000mAh. Memoria interna de 128GB. Con reconocimiento facial y sensor de huella dactilar."
    },
    {
      id: 37,
      name: 'Xiaomi Redmi Note 11 Pro 5G ',
      href: '#',
      imageSrc: 'https://i.ibb.co/MVZkPkt/XIAOMI-REDMI-NOTE-11-PRO-5-G.webp',
      imageAlt: "Xiaomi Redmi Note 11 Pro 5G ",
      price: 281999,
      brand: 'Xiaomi',
      min: 1,
      stock: 10,
      category: "Celular",
      description: "Dispositivo liberado para que elijas la compañía telefónica que prefieras. Compatible con redes 5G. Pantalla AMOLED de 6.67. Tiene 3 cámaras traseras de 108Mpx/8Mpx/2Mpx. Cámara delantera de 16Mpx. Procesador Snapdragon 695 Octa-Core de 2.2GHz con 6GB de RAM. Batería de 5000mAh. Memoria interna de 128GB. Resistente a las salpicaduras. Con reconocimiento facial y sensor de huella dactilar. Resistente al polvo."
    },
    {
      id: 38,
      name: 'Xiaomi Redmi Note 11S Dual SIM 128 GB ',
      href: '#',
      imageSrc: 'https://i.ibb.co/jZpjTB1/XIAOMI-REDMI-NOTE-11-S-DUAL-SIM.webp',
      imageAlt: "Xiaomi Redmi Note 11S Dual SIM 128 GB ",
      price: 149999,
      brand: 'Xiaomi',
      min: 1,
      stock: 10,
      category: "Celular",
      description: "Dispositivo liberado para que elijas la compañía telefónica que prefieras. Pantalla AMOLED de 6.43. Tiene 4 cámaras traseras de 108Mpx/8Mpx/2Mpx/2Mpx. Cámara delantera de 16Mpx. Procesador MediaTek Helio G96 Octa-Core de 2.05GHz con 6GB de RAM. Batería de 5000mAh. Memoria interna de 128GB. Con reconocimiento facial y sensor de huella dactilar. Resistente al polvo."
    },
    {
      id: 39,
      name: 'Moto G13 Dual SIM 128 GB azul difuso 4 GB RAM',
      href: '#',
      imageSrc: 'https://i.ibb.co/hdqvCL6/MOTO-EDGE-30-FUSION.webp',
      imageAlt: "Moto G13 Dual SIM 128 GB azul difuso 4 GB RAM",
      price: 79999,
      stock: 10,
      brand: 'Motorola',
      category: "Celular",
      description: " Graba videos 4K y captura retratos espectaculares y paisajes increíbles con el sistema de dos cámaras. Toma grandes fotos con poca luz gracias al modo Noche. Disfruta colores reales en las fotos, videos y juegos con la pantalla Liquid Retina de 6.1 pulgadas (3). Aprovecha un rendimiento sin precedentes en los juegos, la realidad aumentada y la fotografía con el chip A13 Bionic. Haz mucho más sin necesidad de volver a cargar el teléfono gracias a su batería de larga duración (2). Y no te preocupes si se moja, el iPhone 11 tiene una resistencia al agua de hasta 30 minutos a una profundidad máxima de 2 metros (1). "
    },
    {
      id: 40,
      name: 'Moto G42 128 GB verde atlántico 4 GB RAM',
      href: '#',
      imageSrc: 'https://i.ibb.co/5LLjsq0/MOTO-G13-DUAL.webp',
      imageAlt: "Moto G42 128 GB verde atlántico 4 GB RAM",
      price: 88899,
      stock: 10,
      brand: 'Motorola',
      category: "Celular",
      description: "Dispositivo liberado para que elijas la compañía telefónica que prefieras. Pantalla OLED de 6.4. Tiene 3 cámaras traseras de 50Mpx/8Mpx/2Mpx. Cámaras delanteras de 16Mpx. Procesador Snapdragon 680 4G Octa-Core de 2.4GHz con 4GB de RAM. Batería de 5000mAh. Memoria interna de 128GB. Resistente a las salpicaduras. Con reconocimiento facial y sensor de huella dactilar. "
    },
    {
      id: 41,
      name: 'Moto G23 128 GB pearl white 4 GB RAM',
      href: '#',
      imageSrc: 'https://i.ibb.co/YcPyvG6/MOTO-G23.webp',
      imageAlt: "Moto G23 128 GB pearl white 4 GB RAM",
      price: 85999,
      stock: 10,
      brand: 'Motorola',
      category: "Celular",
      description: "Dispositivo liberado para que elijas la compañía telefónica que prefieras. Pantalla IPS de 6.5. Tiene 3 cámaras traseras de 50Mpx/5Mpx/2Mpx. Cámara delantera de 16Mpx. Procesador Mediatek MT6769Z Helio G85 Octa-Core de 2GHz con 4GB de RAM. Batería de 5000mAh. Memoria interna de 128GB. Resistente al agua. Con sensor de huella dactilar."
    },
    {
      id: 42,
      name: 'Motorola Edge 30 Fusion 256 GB lazuli blue 12 GB RAM',
      href: '#',
      imageSrc: 'https://i.ibb.co/b13xb1T/MOTO-G42.webp',
      imageAlt: "Motorola Edge 30 Fusion 256 GB lazuli blue 12 GB RAM",
      price: 249999,
      stock: 10,
      brand: 'Motorola',
      category: "Celular",
      description: " Dispositivo liberado para que elijas la compañía telefónica que prefieras. Compatible con redes 5G. Pantalla POLED de 6.55. Tiene 3 cámaras traseras de 50Mpx/13Mpx/2Mpx. Cámaras delanteras de 32Mpx. Procesador Snapdragon 888+ 5G Octa-Core de 2.99GHz con 12GB de RAM. Batería de 4400mAh. Memoria interna de 256GB. Resistente al agua. Con reconocimiento facial y sensor de huella dactilar. Resistente al polvo."
    },
    {
      id: 43,
      name: 'Celular Motorola Moto G72 128/6gb Ram Azul Nuevo',
      href: '#',
      imageSrc: 'https://i.ibb.co/6JjGxyw/MOTO-G72.jpg',
      imageAlt: "Celular Motorola Moto G72 128/6gb Ram Azul Nuevo",
      price: 133999,
      stock: 10,
      brand: 'Motorola',
      category: "Celular",
      description: " Dispositivo liberado para que elijas la compañía telefónica que prefieras. Pantalla POLED de 6.6. Tiene 3 cámaras traseras de 108Mpx/8Mpx/2Mpx. Cámara delantera de 16Mpx. Procesador MediaTek Helio G99 Octa-Core de 2.2GHz con 6GB de RAM. Batería de 5000mAh. Memoria interna de 128GB. Resistente al agua. Con reconocimiento facial y sensor de huella dactilar. "
    },
    {
      id: 44,
      name: 'Moto G52 128 GB azul 6 GB RAM',
      href: '#',
      imageSrc: 'https://i.ibb.co/ww1J3n4/MOTO-G52.webp',
      imageAlt: "Moto G52 128 GB azul 6 GB RAM",
      price: 128999,
      stock: 10,
      brand: 'Motorola',
      category: "Celular",
      description: " Dispositivo liberado para que elijas la compañía telefónica que prefieras. Pantalla AMOLED de 6.6. Tiene 3 cámaras traseras de 50Mpx/8Mpx/2Mpx. Cámaras delanteras de 16Mpx. Procesador Snapdragon 680 Octa-Core de 2.4GHz con 6GB de RAM. Batería de 5000mAh. Memoria interna de 128GB. Resistente a las salpicaduras. Con reconocimiento facial y sensor de huella dactilar. Resistente al polvo."
    },
    {
      id: 45,
      name: 'Samsung Galaxy A34 5G 5G 128 GB awesome lime 6 GB RAM',
      href: '#',
      imageSrc: 'https://i.ibb.co/gtnZqMv/SM-A04-DUAL-SIM.jpg',
      imageAlt: "Samsung Galaxy A34 5G 5G 128 GB awesome lime 6 GB RAM",
      price: 114599,
      stock: 10,
      brand: 'Samsung',
      category: "Celular",
      description: " Dispositivo desbloqueado para que elijas la compañía telefónica que prefieras.Compatible con redes 5G.Pantalla Super AMOLED de 6.6.Tiene 3 cámaras traseras de 48Mpx/8Mpx/5Mpx.Cámara delantera de 13Mpx.Procesador Mediatek MT6877V Dimensity 1080 Octa-Core de 2.6GHz con 6GB de RAM.Batería de 5000mAh.Memoria interna de 128GB.Resistente al agua.Con reconocimiento facial y sensor de huella dactilar.Resistente al polvo"
    },
    {
      id: 46,
      name: 'Samsung Galaxy S23 Ultra Dual SIM 256 GB phantom black 12 GB',
      href: '#',
      imageSrc: 'https://i.ibb.co/7RdfySN/SM-A04-S-DUAL-SIM.webp',
      imageAlt: "Samsung Galaxy S23 Ultra Dual SIM 256 GB phantom black 12 GB",
      price: 449999,
      stock: 10,
      brand: 'Samsung',
      category: "Celular",
      description: " Dispositivo desbloqueado para que elijas la compañía telefónica que prefieras.Compatible con redes 5G.Pantalla AMOLED de 6.78.Tiene 4 cámaras traseras de 200Mpx/12Mpx/10Mpx/10Mpx.Cámaras delanteras de 12MpxProcesador Snapdragon 8 Gen 2 Octa-Core de 3GHz con 12GB de RAM.Batería de 5000mAh con carga inalámbrica.Memoria interna de 256GB.A prueba de agua.Con reconocimiento facial y sensor de huella dactilar."
    },
    {
      id: 47,
      name: 'Samsung Galaxy S21 FE 5G (Exynos) 5G Dual SIM 256 GB olive 8 GB RAM',
      href: '#',
      imageSrc: 'https://i.ibb.co/8rP6r0V/SM-A34-5-G.webp',
      imageAlt: "Samsung Galaxy S21 FE 5G (Exynos) 5G Dual SIM 256 GB olive 8 GB RAM",
      price: 128662,
      stock: 10,
      brand: 'Samsung',
      category: "Celular",
      description: " Dispositivo desbloqueado para que elijas la compañía telefónica que prefieras.Compatible con redes 5G.Pantalla Dynamic AMOLED 2X de 6.4.Tiene 3 cámaras traseras de 12Mpx/12Mpx/8Mpx.Cámara delantera de 32Mpx.Procesador Exynos 2100 Octa-Core de 2.9GHz con 8GB de RAM.Batería de 4500mAh con carga inalámbrica.Memoria interna de 256GB.Resistente al agua.Resistente al polvo."
    },
    {
      id: 48,
      name: 'Samsung Galaxy A04 Dual SIM 64 GB negro 4 GB RAM',
      href: '#',
      imageSrc: 'https://i.ibb.co/KmvSvLs/SM-S21-FE-5-G.webp',
      imageAlt: "Samsung Galaxy A04 Dual SIM 64 GB negro 4 GB RAM",
      price: 499999,
      stock: 10,
      brand: 'Samsung',
      category: "Celular",
      description: "Dispositivo desbloqueado para que elijas la compañía telefónica que prefieras.Pantalla PLS de 6.5.Tiene 2 cámaras traseras de 50Mpx/2Mpx.Cámara delantera de 5Mpx.Procesador Unisoc SC9863A Octa-Core de 1.6GHz con 4GB de RAM.Batería de 5000mAh.Memoria interna de 64GB"
    },
    {
      id: 49,
      name: 'Samsung Galaxy Z Flip4 5G 256 GB graphite 8 GB RAM',
      href: '#',
      imageSrc: 'https://i.ibb.co/7XcMXw5/SM-Z-FLIP4-5-G.jpg',
      imageAlt: "Samsung Galaxy Z Flip4 5G 256 GB graphite 8 GB RAM",
      price: 128962,
      stock: 10,
      brand: 'Samsung',
      category: "Celular",
      description: " Dispositivo desbloqueado para que elijas la compañía telefónica que prefieras.Compatible con redes 5G.Pantalla plegable con una extensión total de 6.7 y resolución de 1080px x 2640px.Tiene 2 cámaras traseras de 12Mpx/12Mpx.Cámara delantera de 10Mpx.Procesador Snapdragon 8+ Gen 1 Octa-Core de 3.18GHz con 8GB de RAM.Batería de 3700mAh con carga inalámbrica.Memoria interna de 256GB.Resistente al agua.Con reconocimiento facial y sensor de huella dactilar.Pantalla secundaria táctil de 1.9.Tarjeta eSIM incluida en tu dispositivo"
    },
    {
      id: 50,
      name: 'Samsung Galaxy A04s Dual SIM 128 GB negro 4 GB RAM',
      href: '#',
      imageSrc: 'https://i.ibb.co/7RdfySN/SM-A04-S-DUAL-SIM.webp',
      imageAlt: "Samsung Galaxy A04s Dual SIM 128 GB negro 4 GB RAM",
      price: 694999,
      stock: 10,
      brand: 'Samsung',
      category: "Celular",
      description: " Dispositivo desbloqueado para que elijas la compañía telefónica que prefieras.Pantalla PLS de 6.5.Tiene 3 cámaras traseras de 50Mpx/2Mpx/2Mpx.Cámara delantera de 5Mpx.Procesador Exynos 850 Octa-Core de 2GHz con 4GB de RAM.Batería de 5000mAh.Memoria interna de 128GB.Con reconocimiento facial y sensor de huella dactilar."
    },
  
  ]
  // productsDataPhones.js
  // 37 KB