export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCT_NAME = "GET_PRODUCT_NAME";
export const GET_DETAILS = "GET_DETAILS";
export const FILTER_BY_BRAND = "FILTER_BY_BRAND";
export const FILTER_CREATED = "FILTER_CREATED";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const ORDER_BY_PRICE = "ORDER_BY_PRICE";
export const POST_PRODUCT = "POST_PRODUCT";
export const CLEAR_DETAIL = "CLEAR_DETAIL";
export const CLEAR_FILTER = "CLEAR_FILTER";


